version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      # - REACT_APP_BACKEND_URL=http://localhost:5000
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - '3000:3000'
    expose:
      - '3000'
    networks:
      - integration
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
  backend:
    build: ./backend
    container_name: backend
    environment:
      - PORT=5000
    expose:
      - '5000'
    ports:
      - "5000:5000"
    command: npm run start
    networks:
      - integration
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  db:
    image: postgres:alpine
    restart: always
    container_name: "postgres"
    env_file:
      - .env
    environment:
      - PORT=5000
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    ports:
      - 5432:5432
    networks:
      - integration
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
networks:
  integration:
    driver: bridge
volumes:
  postgres-db:
